language: node_js
node_js:
- 'lts/*'

cache:
  directories:
  - node_modules

addons:
  ssh_known_hosts: full.stack.dev

before_install:
- openssl aes-256-cbc -K $encrypted_2b95ec92a9a2_key -iv $encrypted_2b95ec92a9a2_iv
  -in deploy.enc.key -out deploy-key -d

install:
- npm install

script:
- chmod 600 deploy-key
- mv deploy-key ~/.ssh/id_rsa
- npm run build
- npm test
- npm audit
- cd dist/
- git init
- git remote add deploy "deploy@full.stack.dev:/home/deploy/site"
- git config user.name "Travis CI"
- git config user.email "travis@full.stack.dev"
- git add .
- git commit -m "Deploying via Travis"
- git push --force deploy master

# https://web.archive.org/web/20170101080621/https://kjaer.io/travis/
