name: commitizen

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate-commits:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: aevea/commitsar@master
