name: commitizen

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: aevea/commitsar@master
