name: markdown

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  scan-links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@master
