name: npm

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: npm audit --audit-level=moderate
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: npm ci
    - run: npm run lint
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: npm ci
    - run: npm run build
      env:
        CI: true
    - uses: actions/upload-artifact@master
      with:
        name: dist
        path: dist
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: [build, lint, audit]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@master
      with:
        name: dist
    - uses: appleboy/scp-action@v0.0.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: dist
        target: dist
        strip_components: 1
    - uses: appleboy/ssh-action@v0.0.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: sudo service nginx reload
  lighthouse:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: treosh/lighthouse-ci-action@master
        with:
          urls: https://hi.im.borja.and.im.a.full.stack.dev
          configPath: .github/lighthouse/config.json
          uploadArtifacts: true
  observatory:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
    - run: sudo npm install -g observatory-cli
    - run: observatory hi.im.borja.and.im.a.full.stack.dev --min-grade A+
